### ISSUE TITLE
OptionalDependencies must also be removed from package.json

### ISSUE THREAD

**Issue by palmerj3** [JamieMason/shrinkpack#74] opened 2016-09-08 12:55 UTC
According to NPM [if you remove optionalDependencies in npm-shrinkwrap.json but they still exist in package.json NPM will install them anyways](https://github.com/npm/npm/pull/13579#issuecomment-243898968). I totally disagree with this behavior and will be working on a NPM PR to remove this behavior entirely. But I think you could handle this in shrinkpack.

Certainly removing optionalDeps from top level package.json would be doable but it's not clear to me right now if you will also need to handle this for lower level packages.

**Comment by JamieMason** [comment] 2016-09-25 14:50
Closing as duplicate of #75 as there is more discussion in that thread.

**Closed as completed by JamieMason** 2016-09-25 14:50 UTC
Labels: Type: Duplicate
