### ISSUE TITLE
Change made in npm 3.8.8 breaks shrinkpacked projects

### ISSUE THREAD

**Issue by gleseur** [JamieMason/shrinkpack#45] opened 2016-05-20 15:43 UTC
We are not able to run npm install with recent npm versions
#### Expected behaviour

npm install with success on all (at least recent npm versions)

For now, we'll just keep on using a compatible npm version, but at some point, this is going to be an issue.
...
#### Actual behaviour

Did not try for all npm versions, but with 3.8.3 it is working fine, while with 3.8.9 or 3.9.2 (currently latest) npm install no longer finds the files.

From the error logs, the issue is pretty clear, the meaning of './' changed in a version between 3.8.3 and 3.8.9 and now, for dependencies, npm is building the path starting from the node_modules/package repertory instead of the working directory
...
#### Steps to reproduce

on a shrinkwrapped project
npm install -g npm@3.8.3
rm -rf node_modules
npm install
=> all good

npm install -g npm@3.9.2
rm -rf node_modules
npm install
=> all dependencies are failing
...
#### Software versions used

```
OS         :  Ubuntu 14.04
node.js    :  5.10.1
npm        : 3.8.3 => ok, 3.8.9 or 3.9.2 => not ok
shrinkpack : 0.12.3
```
#### Log output when running shrinkpack

```
$ rm -rf node_modules
$ npm install
Running node v5.10.1
npm ERR! addLocal Could not install /.../node_modules/dom-serializer/node_shrinkwrap/domelementtype-1.1.3.tgz
npm ERR! addLocal Could not install /.../node_modules/dom-serializer/node_shrinkwrap/entities-1.1.1.tgz
npm ERR! addLocal Could not install /.../node_modules/readline2/node_shrinkwrap/ansi-regex-1.1.1.tgz
npm ERR! addLocal Could not install /.../node_modules/readline2/node_shrinkwrap/mute-stream-0.0.4.tgz
npm ERR! addLocal Could not install /.../node_modules/readline2/node_shrinkwrap/strip-ansi-2.0.1.tgz
npm ERR! addLocal Could not install /.../node_modules/camelcase-keys/node_shrinkwrap/camelcase-2.1.0.tgz
npm ERR! addLocal Could not install /.../node_modules/indent-string/node_shrinkwrap/repeating-2.0.0.tgz
...
```

**Comment by zenyr** [comment] 2016-05-21 10:42
npm 3.8.7 also seems to work, I guess? 
(used `npm i -g npm3` a few weeks ago, resulting `npm3 -v` == 3.8.7 & `npm -v` == 2.15.0)

A colleague of mine who had set her system up recently is also having this issue. 
(not sure of the exact npm@3 version but updating `npm` was not working for her, while 100% identical shrinkwrap.json had worked on mine & another colleague just fine.. removing shrinkwrap.json and installing over HTTP ~~fixed~~workaround-ed the issue temporarily. )

**Comment by aliebuck** [comment] 2016-05-23 01:36
Can also confirm that the issue is replicable on npm 3.8.8 and newer.

**Comment by JamieMason** [comment] 2016-05-23 10:36
Thanks @jacobbuck @zenyr @gleseur, I noticed this myself recently too. Another `npm` quirk to add to the ever-growing list to work around 😣

**Comment by JamieMason** [comment] 2016-05-30 17:21
**Summary of what's known so far;**

1) It can be reproduced using the following steps

```
$ npm i -g shrinkpack
$ mkdir some-project
$ cd some-project
$ npm init -y
$ npm install --save ava
$ npm shrinkwrap
$ shrinkpack
$ rm -rf node_modules
$ npm i
```

2) The [package.json](https://github.com/JamieMason/shrinkpack/files/289920/package.json.txt) and [npm-shrinkwrap.json](https://github.com/JamieMason/shrinkpack/files/289921/npm-shrinkwrap.json.txt) are attached to this issue.
3) The above works up to version v3.8.7 of npm, then fails in v3.8.8.
4) v3.8.8 and up gives the following error for some (but not all) of the entries in `npm-shrinkwrap.json`.

```
npm ERR! addLocal Could not install /Users/jamie/Sites/test/node_modules/meow/node_shrinkwrap/minimist-1.2.0.tgz
```

5) The correct path is `/Users/jamie/Sites/test/meow/node_shrinkwrap/minimist-1.2.0.tgz`.
6) `node_modules` is being inserted into some of the file paths read from npm-shrinkwrap.json in https://github.com/npm/npm/blob/cde367fbb6eebc5db68a44b12a5c7bea158d70db/lib/utils/child-path.js#L9.
7) These are the [commits to npm between v3.8.7 and v3.8.8](https://github.com/npm/npm/compare/cc985cc...db5d7cd).

@iarna I'd be really grateful if you could offer some ideas as to what might have caused this difference in behaviour. Is this an intentional change with a recommended workaround? Or could it perhaps be some kind of regression. 

Any input you could give would be hugely welcome.

Thanks all.

**Comment by JamieMason** [comment] 2016-05-30 17:33
Among the changes were updates to these packages used by npm;

https://github.com/npm/npm-package-arg
– Parse the things that can be arguments to `npm install` http://npm.im/npm-package-arg

https://github.com/npm/realize-package-specifier
– Like npm-package-arg, but more so, producing full file paths and differentiating local tar and directory sources.

It's probable that it was a change in one of these two projects that has introduced this behaviour in npm.

**Comment by JamieMason** [comment] 2016-05-30 17:37
cc-ing @zkat – would you be able to help us please?

**Comment by iarna** [comment] 2016-06-01 20:12
Hey you all:

So, the change here was that local-type dependencies are resolved relative to the package that required them.

This is, I think, absolutely the correct behavior for specs coming from the `package.json`.

But it does seem confusing (and probably wrong) for `npm-shrinkwrap.json`, there I think it should resolve relative to the location of the `npm-shrinkwrap.json`. Initial testing shows that this would fix the class of errors you all are seeing.

Work remaining to get this fixed in npm:
- I need to write a simple network-free reproducer. (This should be super easy.)
- I need to make sure that `npm shrinkwrap` on existing local deps produces compatible specs.

My current plan is to tackle shrinkwrap related big-bugs next (and this is one of those), so hopefully we'll get this out the door soon.

**Comment by JamieMason** [comment] 2016-06-01 20:19
Brilliant Rebecca, thanks so much 👍😊

**Comment by medifle** [comment] 2016-06-27 03:12
npm@3.9.5

# 

Updates 6-28

I experienced the path problem when I was using shrinkpack to `npm install`.

So I went for npm-ducttape. No path problem occurs.

# 

[npm-ducttape](https://github.com/DeadAlready/npm-ducttape) create an npm-shrinkwrap.json like this

``` json
"dependencies": {
  "abbrev": {
    "dependencies": {},
    "version": "1.0.9",
    "from": "abbrev@>=1.0.0 <2.0.0",
    "resolved": "file:.packages/abbrev-1.0.9.tgz"
  },
  "accepts": {
    "dependencies": {},
    "version": "1.2.13",
    "from": "accepts@>=1.2.13 <1.3.0",
    "resolved": "file:.packages/accepts-1.2.13.tgz"
  },
}
```

It works fine without throwing the path error.

**Comment by markerikson** [comment] 2016-06-27 03:23
Oh hey.  Saw this the other day when I was getting a new dev spun up on the prototype I've been working on, but didn't manage to pull up this issue while trying to figure it out.  Also apparently didn't read this issue all that closely when I +1'd it, either, because it didn't cross my mind.  Glad to know there's at least a known issue involved.

**Comment by JamieMason** [comment] 2016-06-27 07:10
@medifle can you clarify whether you were using `shrinkpack` or `npm-ducttape` please? I can't tell from your comment, thanks.

**Comment by JamieMason** [comment] 2016-06-27 07:26
Update: I've tried npm@3.10.2 this morning and can confirm the issue still stands. npm have been really helpful and have said a fix will come when they get the time, but please continue with `<3.8.8` until then.

**Comment by iarna** [comment] 2016-06-27 22:57
Hi all! My plan is to get a fix for this into this week's npm release. It's a short week for me (I'm only in today and tomorrow) but I'm optimistic. My colleague @zkat will be handling the release this week.

**Comment by iarna** [comment] 2016-07-01 04:16
The fix was released today in 3.10.4!

**Comment by JamieMason** [comment] 2016-07-01 08:56
Woo! thanks @iarna

**Closed as completed** 2016-07-01 14:27 UTC
Labels: Status: Blocked, Priority: High, Type: Upstream Bug

**Comment by markerikson** [comment] 2016-08-15 17:55
Getting a colleague set up to work on my project, and he just ran into this.  Following my setup instructions, he made sure to update NPM to latest, and is currently using 3.10.6.  I'd still been using an older version of NPM myself, but tried updating my NPM to latest, cloned our repo to a new folder, ran `npm install`, and I see the same thing: a wall of `npm ERR! addLocal Could not install $TARBALL` errors.

Kinda confused - based on the discussion, I thought 3.10.4+ would be fine.

**Comment by JamieMason** [comment] 2016-08-15 18:06
I've had an issue a few times where I ran `npm install -g npm` and it didn't actually update it to the latest version available for some reason.

Is `npm -v` showing `3.10.6`? In the past I've had to run eg. `npm i -g npm@3.10.6` to get it to actually install the version I wanted.

**Comment by markerikson** [comment] 2016-08-15 18:07
Yeah, his box showed 3.10.6, and mine did as well after I upgraded.

**Comment by JamieMason** [comment] 2016-08-15 18:18
Ah ok. As a start I've just added 3.10.7 to the Travis job and triggered this build https://travis-ci.org/JamieMason/shrinkpack/builds/152454483. If that passes could you open a new issue which tries to explain how to reproduce please?

**Comment by sandro-pasquali** [comment] 2016-09-20 18:24
Just bumped against this myself. Luckily there is google, which led me here, but it might be useful to mention this somewhere in the readme.

**Comment by JamieMason** [comment] 2016-09-20 19:12
Thanks @sandro-pasquali, I've made a note in the installation section of the readme 👍
