### ISSUE TITLE
npm shrinkwrap complaints about extraneous and missing packages

### ISSUE THREAD

**Issue by gajus** [JamieMason/shrinkpack#14] opened 2016-01-05 10:33 UTC
I am trying to test `shrinkpack`, but I fail at the `shrinkwrap` step. Looking for help understanding this issue and how to fix it.

Steps to reproduce.

``` sh
git clone https://github.com/gajus/canonical.git
cd ./canonical
npm install
npm prune
npm dedupe
npm shrinkwrap --dev
```

The error:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/gajus/.nvm/versions/node/v5.3.0/bin/node" "/Users/gajus/.nvm/versions/node/v5.3.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: async@1.5.0 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/async
npm ERR! extraneous: debug@0.7.4 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/debug
npm ERR! extraneous: escape-string-regexp@1.0.3 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/escape-string-regexp
npm ERR! extraneous: mime-types@2.1.7 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/mime-types
npm ERR! extraneous: once@1.1.1 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/once
npm ERR! extraneous: readable-stream@1.1.13 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/readable-stream
npm ERR! extraneous: rimraf@2.4.4 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/rimraf
npm ERR! extraneous: sshpk@1.7.0 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/sshpk
npm ERR! extraneous: tunnel-agent@0.4.1 /Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/node_modules/tunnel-agent
npm ERR! missing: npmlog@0 || 1, required by node-gyp@3.0.3
npm ERR! missing: rimraf@~2.4.0, required by node-pre-gyp@0.6.17
npm ERR! missing: debug@~0.7.2, required by tar-pack@3.1.0
npm ERR! missing: once@~1.1.1, required by tar-pack@3.1.0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gajus/Documents/dev/canonical-code-style/canonical/npm-debug.log
```

**Comment by gajus** [comment] 2016-01-05 10:53
This issue has been reported quite a few times https://github.com/npm/npm/issues/4435.

Interestingly,

``` sh
npm install
npm prune
npm dedupe
npm install
npm shrinkwrap --dev
```

made it work.

**Comment by JamieMason** [comment] 2016-01-05 11:27
Hey @gajus, 
I've had similar problems in the past and am still working to narrow down exactly what the cause is. 

Some things I've noticed though are that wildcards like `^` and `*` etc can make the resulting dependency graph less predictable, but even then IIRC subsequent runs of `npm shrinkwrap` one after another result in subtly different `npm-shrinkwrap.json` files and I _think_ this is somehow related.

Packages which list git tags as dependencies etc can also make things more difficult for projects like this, and require some extra attention.

I don't have anything more solid just yet unfortunately.

**Comment by JamieMason** [comment] 2016-03-27 21:32
Closing as this is an issue with npm and shrinkwrap itself, but I noticed that @thewoolleyman has been putting this together https://github.com/thewoolleyman/npm-shrinkwrap-helper which contains some really useful info on how to avoid the problems described here.

**Closed as completed by JamieMason** 2016-03-27 21:32 UTC
Labels: Type: Question
